name: 'SVG to PNG Converter'
description: 'A GitHub Action to convert SVG files to PNG'
author: 'Your Name'
inputs:
  svg-folder:
    description: 'The folder containing SVG files'
    required: true
    default: 'svg-files'
  png-folder:
    description: 'The folder to store converted PNG files'
    required: true
    default: 'png-copy'
  github-token:
    description: 'GitHub token to commit changes'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.svg-folder }}
    - ${{ inputs.png-folder }}
    - ${{ inputs.github-token }}
